### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by crotin1111** [blackmatch/pornhub-downloader#16]
C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\src\lib\scrapy.js:128
      return item.videoUrl.length > 0;
                           ^

TypeError: Cannot read property 'length' of undefined
    at C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\src\lib\scrapy.js:128:28
    at arrayFilter (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\node_modules\lodash\lodash.js:582:11)
    at Function.filter (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\node_modules\lodash\lodash.js:9173:14)
    at parseDownloadInfo (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\src\lib\scrapy.js:127:13)
    at Request._callback (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\src\lib\scrapy.js:157:21)
    at Request.self.callback (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\node_modules\request\request.js:186:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\node_modules\request\request.js:1163:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (C:\Users\Sheldon Gelinas\.idlerc\pornhub-downloader\node_modules\request\request.js:1085:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pornhub-downloader@2.2.2 start: `node ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pornhub-downloader@2.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by pervmaster** [comment]
This [patch](https://gist.githubusercontent.com/pervmaster/2232ad14d3c41982f4206571f57a10d0/raw/d1312332ffa4ee8215ab652be89593398acfc145/fix-parsing-nested-brackets.patch) should fix the issue.

**Comment by pervmaster** [comment]
Also, use this [patch](https://gist.githubusercontent.com/pervmaster/5b2f75c286036e39214756a090e7d378/raw/90f84289afaf45536ccabe6d33877b65e87ce3bf/fix-exclude-hls-format) to remove HTTP Live Streaming videos, which could interfere with results.

**Comment by AKAlilghost** [comment]
I also have this problem
