### ISSUE TITLE
npm start报错，找不到text什么的

### ISSUE THREAD

**Issue by glimjoe** [blackmatch/pornhub-downloader#2]
> pornhub-downloader@1.0.0 start E:\pornhub-downloader-master1
> babel-node ./src --presets es2015,stage-3

E:\pornhub-downloader-master1\src\lib\pornhub.js:33
      var $ = _cheerio2.default.load(res.text);
                                        ^

TypeError: Cannot read property 'text' of undefined
    at E:/pornhub-downloader-master1/src/lib/pornhub.js:28:30
    at Request.callback (E:\pornhub-downloader-master1\node_modules\superagent\lib\node\index.js:688:3)
    at ClientRequest.<anonymous> (E:\pornhub-downloader-master1\node_modules\superagent\lib\node\index.js:615:10)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)

**Comment by blackmatch** [comment]
@glimjoe 最新的一次commit已修复，这是因为有时候访问网页访问返回空，无法解析，现在用try catch做了异常判断应该没什么问题了。如有问题重新开这个issue。
